  version: '3.8'

  services:
    nginx:
      image: nginx:latest
      ports:
        - "90:90"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - auth-service
      networks:
        - my-network

    user-db:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: BayerLeverkusen
      ports:
        - "5433:5432"
      networks:
        - my-network

    auth-service:
      build:
        context: ./identity-service 
        dockerfile: dockerfile
      ports:
        - "8081:8081"
      depends_on:
        - user-db
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/BayerLeverkusen
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
      networks:
        - my-network

  networks:
    my-network:
      driver: bridge