FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /workspace

COPY pom.xml /workspace/pom.xml
COPY src /workspace/src

RUN mvn -B clean install -DskipTests

FROM openjdk:17-jdk-alpine
WORKDIR /opt
ENV PORT 8081
EXPOSE 8081
COPY --from=build workspace/target/*.jar /opt/app.jar
CMD ["java", "-jar", "app.jar"]