package com.example.marketingmanagerservice.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name="BoughtItem")
public class BoughtItem {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private Long articleId;
    private int quantity;
    private double price;
    private LocalDateTime dateOfBuying;

    // Getters and setters can be generated by Lombok
}
